server:
  port: 9011

greeting:
  message: Welcome to the Simple Micro-Service

spring:
  application:
    name: user-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka