server:
  port: 8888

spring:
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:\\\C:\Users\ses12\IdeaProjects\MicroService-Project-Eureka\configservice\src\main\resources\native-file-repo
        #git:
          #uri: file:\\\C:\Users\ses12\IdeaProjects\MicroService-Project-Eureka\configservice\src\main\resources\git-local-repo
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,busrefresh
